version: '3'

services:
    app:
        container_name: app
        build: .
        command: npm run start:debug
        env_file: .env
        ports:
            - ${PORT}:${PORT}
        networks:
            - webnet
        volumes:
            - .:/app
            - /app/node_modules
        restart: on-failure
        depends_on:
            - db

    db:
        image: postgres:alpine
        env_file: .env
        environment:
            POSTGRES_DB: ${PG_DB}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASS} 
            PG_DATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"
        expose:
        - '5432'
        networks:
            - webnet
        volumes:
            - pgdata:/var/lib/postgresql/data

            
networks:
    webnet:

volumes:
    pgdata: